# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08b0a49627746365cee0dac1aa90c30a917f555dc23d1b2fe86bb859afd4e26f3e89ff68807323995241cc838e7737c9b97bd2dff4bf7d1a30af092714c83d55

test:
  secret_key_base: 6eb4dc37b723a5e49ea7277faed7fc7b530cbd89415560ea7e522d8491bb797bac73d2df936bc797c4414c85957be6c6da1557075ae556d97742d7cdf276bfb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
